# Netlify configuration for HomeLinkGH website
[build]
  # Deploy from root directory since website files are at root level
  publish = "."
  
  # No build command needed since we have static HTML files
  command = ""

# Custom headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com https://fonts.googleapis.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com; font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com; img-src 'self' data: https:; connect-src 'self'"

# SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Enable HTTPS redirects
[[redirects]]
  from = "http://homelinkgh.com/*"
  to = "https://homelinkgh.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.homelinkgh.com/*"
  to = "https://homelinkgh.com/:splat"
  status = 301
  force = true

# Handle www subdomain
[[redirects]]
  from = "https://www.homelinkgh.com/*"
  to = "https://homelinkgh.com/:splat"
  status = 301
  force = true

[build.environment]
  NODE_VERSION = "18"