<<<<<<< HEAD
[build]
  publish = "."
  
# Temporarily disable HTTPS redirects to fix TLS issues
# [[redirects]]
#   from = "http://homelinkgh.com/*"
#   to = "https://homelinkgh.com/:splat"
#   status = 301
#   force = true

# [[redirects]]
#   from = "http://www.homelinkgh.com/*"
#   to = "https://homelinkgh.com/:splat"
#   status = 301
#   force = true

# [[redirects]]
#   from = "https://www.homelinkgh.com/*"
#   to = "https://homelinkgh.com/:splat"
#   status = 301
#   force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
=======
# Netlify configuration for HomeLinkGH website
[build]
  # Deploy from root directory since website files are at root level
  publish = "."
  
  # No build command needed since we have static HTML files
  command = ""

# Custom headers for security and performance
>>>>>>> a03eec9f92f7cc7de546588bc06ae759a261f76a
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
<<<<<<< HEAD
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    # Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com https://fonts.googleapis.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com; font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com; img-src 'self' data: https:; connect-src 'self'"

[build.environment]
  NODE_VERSION = "18"
=======
    Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self'"

# Enable HTTPS redirects
[[redirects]]
  from = "http://homelinkgh.com/*"
  to = "https://homelinkgh.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.homelinkgh.com/*"
  to = "https://homelinkgh.com/:splat"
  status = 301
  force = true

# Handle www subdomain
[[redirects]]
  from = "https://www.homelinkgh.com/*"
  to = "https://homelinkgh.com/:splat"
  status = 301
  force = true
>>>>>>> a03eec9f92f7cc7de546588bc06ae759a261f76a
